name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Test frontend
        working-directory: frontend
        run: npm test

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Test backend
        working-directory: backend
        env:
          MONGO_URI: mongodb://localhost:27017/product-app
          #MONGO_URI: ${{ secrets.MONGO_URI_PROD }}
        run: npm test
